# Generated by Django 2.2.6 on 2019-10-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='lastname',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='firstname',
            new_name='name',
        ),
    ]
