# Generated by Django 2.2.6 on 2019-10-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191027_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
    ]
